### ISSUE TITLE
不能播放任何音乐

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/exaile-cn#12]
```
What steps will reproduce the problem?
1.从AUR上安装exaile-cn
2.打开某MP3
3.错误输出

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
V 0.3.1.0

Please provide any additional information below.
Traceback (most recent call last):
  File "/usr/lib/exaile/xlgui/main.py", line 1314, in on_play_clicked
    self.queue.play()
  File "/usr/lib/exaile/xl/player/queue.py", line 140, in play
    self.player.play(track)
  File "/usr/lib/exaile/xl/player/engine_normal.py", line 202, in play
    uri = self._get_track_uri(track)
  File "/usr/lib/exaile/xl/player/engine_normal.py", line 167, in 
_get_track_uri
    path = common.local_file_from_url(uri).encode()
AttributeError: 'module' object has no attribute 'local_file_from_url'

似乎官方原版也有这个问题。


```

Original issue reported on code.google.com by `liuzhen...@gmail.com` on 9 Apr 2010 at 1:42

**Comment by GoogleCodeExporter** [comment]
```
这个貌似是因为原版exaile本身的bug
```

Original comment by `billno...@gmail.com` on 10 Apr 2010 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
有什么方法吗？应该不是少包吧。

搜索的结果很少。

mocp是能正常播放的。
```

Original comment by `liuzhen...@gmail.com` on 10 Apr 2010 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
刚exaile更新到 0.3.1.1
界面输出：
You do not have a decoder installed to handle this file. You might need to 
install
the necessary plugins.
终端输出：
** Message: don't know how to handle audio/mpeg, mpegversion=(int)1, 
layer=(int)3
ERROR   : <gst.Message GstMessageError, gerror=(GstGError)NULL,
debug=(string)"gstplaybasebin.c\(2327\):\ prepare_output\ \(\):\ 
/GstPlayBin:player";
from player at 0x98de408> ['__class__', '__cmp__', '__delattr__', '__dict__',
'__doc__', '__format__', '__getattribute__', '__grefcount__',
'__gstminiobject_init__', '__gtype__', '__hash__', '__init__', '__new__',
'__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', 
'__str__',
'__subclasshook__', 'copy', 'flags', 'parse_async_start', 'parse_buffering',
'parse_buffering_stats', 'parse_clock_lost', 'parse_clock_provide', 
'parse_duration',
'parse_error', 'parse_info', 'parse_new_clock', 'parse_request_state',
'parse_segment_done', 'parse_segment_start', 'parse_state_changed',
'parse_step_done', 'parse_step_start', 'parse_stream_status',
'parse_structure_change', 'parse_tag', 'parse_tag_full', 'parse_warning',
'set_buffering_stats', 'set_seqnum', 'src', 'structure', 'timestamp', 'type']


update:

刚装了一个gstreamer0.10-ffmpeg，就能播放了。不过歌词好像有问
题：
ttp://lyricsfly.com/api/api.php?i=46102e76dde1a145b-exaile.org&a=%%%&t=Kiki%%
http://lyricsfly.com/api/api.php?i=46102e76dde1a145b-exaile.org&a=%%%&t=Kiki%%
'<center>\n<h1>Forbidden access</h1><br>\n<h5>Sorry... you don\'t have access 
to this
folder!</h5><br>\n<a href="../">lyricsfly.com</a>\n</center>'
'<center>\n<h1>Forbidden access</h1><br>\n<h5>Sorry... you don\'t have access 
to this
folder!</h5><br>\n<a href="../">lyricsfly.com</a>\n</center>'

```

Original comment by `liuzhen...@gmail.com` on 10 Apr 2010 at 1:19
