### ISSUE TITLE
装完就无法启动了。。

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/exaile-cn#15]
```
blambin@blambin-laptop:~$ exaile 
Gtk-Message: Failed to load module "globalmenu-gnome": libglobalmenu-gnome.so: 
无法打开共享对象文件: 没有那个文件或目录
INFO    : Loading Exaile 0.3.1.1...
INFO    : Loading settings...
Traceback (most recent call last):
  File "/usr/lib/exaile/exaile.py", line 52, in <module>
    main()
  File "/usr/lib/exaile/exaile.py", line 49, in main
    exaile = main.Exaile()
  File "/usr/lib/exaile/xl/main.py", line 84, in __init__
    self.__init()
  File "/usr/lib/exaile/xl/main.py", line 115, in __init
    self.__show_splash()
  File "/usr/lib/exaile/xl/main.py", line 246, in __show_splash
    import xlgui
  File "/usr/lib/exaile/xlgui/__init__.py", line 40, in <module>
    from xl import covers
ImportError: cannot import name covers
blambin@blambin-laptop:~$ 
```

Original issue reported on code.google.com by `blambinn...@gmail.com` on 23 Jul 2010 at 12:35

**Comment by GoogleCodeExporter** [comment]
```
这个是需要先安装exaile0.3.2的，你用的是0.3.1.1
```

Original comment by `billno...@gmail.com` on 23 Jul 2010 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
额，原来官方源里用的还是旧的
```

Original comment by `blambinn...@gmail.com` on 23 Jul 2010 at 12:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `billno...@gmail.com` on 26 Jul 2010 at 6:31
- Changed state: **Done**
