### ISSUE TITLE
Failed to retrieve playlist, try again.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/exaile-cn#16]
```
点open douban.fm 出来这个错误。操作中终端里没有输出
```

Original issue reported on code.google.com by `blambinn...@gmail.com` on 23 Jul 2010 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
我也出现这个问题
```

Original comment by `wlim...@gmail.com` on 24 Jul 2010 at 11:13

**Comment by GoogleCodeExporter** [comment]
```
这个bug还真没有见过……
```

Original comment by `billno...@gmail.com` on 24 Jul 2010 at 12:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `blambinn...@gmail.com` on 24 Jul 2010 at 1:02

Attachments:
- [截取选区_001.png](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-16/comment-3/截取选区_001.png)

**Comment by GoogleCodeExporter** [comment]
```
麻烦你用附件里的文件替换一下~/.local/share/exaile/plugins/doubanfm
/里的文件，然后用终端运行一下exaile试试
```

Original comment by `billno...@gmail.com` on 24 Jul 2010 at 1:14

Attachments:
- [**init**.py](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-16/comment-4/__init__.py)

**Comment by GoogleCodeExporter** [comment]
```
替换 了 ，这回是点了没反应～～

INFO    : Loading Exaile 0.3.2.0...
INFO    : Loading settings...
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
Traceback (most recent call last):
  File "/home/blambin/.local/share/exaile/plugins/doubanfm/__init__.py", line 299, in active_douban_radio
    songs = self.doubanfm.new_playlist()
  File "/home/blambin/.local/share/exaile/plugins/doubanfm/libdbfm.py", line 87, in new_playlist
    return json.loads(results)['song']
AttributeError: 'module' object has no attribute 'loads'

```

Original comment by `blambinn...@gmail.com` on 24 Jul 2010 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
这个bug看来还真是复杂了,请问你用的python版本是多少……
```

Original comment by `billno...@gmail.com` on 24 Jul 2010 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Python 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) 
[GCC 4.4.3] on linux2


是 这个么
```

Original comment by `blambinn...@gmail.com` on 24 Jul 2010 at 1:45

**Comment by GoogleCodeExporter** [comment]
```
恩，问题基本上搞清楚le，大概是因为python的版本不一样造成
的，反正就是那个json的库的原因
麻烦你试一下把附件里的这个json文件夹copy到~/.local/share/exaile
/plugins/doubanfm下
```

Original comment by `billno...@gmail.com` on 24 Jul 2010 at 1:53

Attachments:
- [json.zip](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-16/comment-9/json.zip)

**Comment by GoogleCodeExporter** [comment]
```
没起到什么 作用～ 
，它能自动读取我的json文件夹么，是不是还应该设置些什么
```

Original comment by `blambinn...@gmail.com` on 24 Jul 2010 at 4:37

**Comment by GoogleCodeExporter** [comment]
```
竟然还不行……应该是可以的,因为在python里一个文件夹就是�
��个库，而在寻找库时会优先寻找本地的库的
这个真的很奇怪，你用的是什么发行版，是ubuntu10.04吗？
ubuntu10.04好像是用simplejson替换了json
麻烦你把附件里的东西解压复制到~/.local/share/exaile/plugins/douba
nfm吧
```

Original comment by `billno...@gmail.com` on 25 Jul 2010 at 12:22

Attachments:
- [doubanfm.tar.gz](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-16/comment-11/doubanfm.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
嗯，这回可以了，不过同时还出现另一个问题， 
就是点击doubanfm的歌曲播放的时候出现 plaback error encountered! 
cancelled . 
同时自带的音乐库里有些歌曲能播放，有些歌曲也是这个错��
�

这时cpu占用已经100％。。


这是点击doubanfm出错时候的终端：

INFO    : Playing 
http://mr1.douban.com/201007251120/dbaae8b8d7e4673820adf7a5bd51ee81/view/song/sm
all/p626764.mp3
Traceback (most recent call last):
  File "/usr/lib/exaile/xlgui/playlist.py", line 542, in on_row_activated
    self.queue.play(track=track)
  File "/usr/lib/exaile/xl/player/queue.py", line 140, in play
    self.player.play(track)
  File "/usr/lib/exaile/xl/common.py", line 105, in wrapper
    return func(self, *__args, **__kw)
  File "/usr/lib/exaile/xl/player/engine_unified.py", line 206, in play
    time = int(track.get_tag_raw("__length")*1000 - duration)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
ERROR   : <gst.Message GstMessageError, gerror=(GstGError)NULL, 
debug=(string)"gstsouphttpsrc.c\(913\):\ gst_soup_http_src_finished_cb\ \(\):\ 
/GstPipeline:pipeline0/GstBin:Stream0/GstURIDecodeBin:uridecodebin3/GstSoupHTTPS
rc:source:\012libsoup\ status\ code\ 1"; from source at 0xa5e1690> 
['__class__', '__cmp__', '__delattr__', '__dict__', '__doc__', '__format__', 
'__getattribute__', '__grefcount__', '__gstminiobject_init__', '__gtype__', 
'__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', 
'__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'copy', 'flags', 
'parse_async_start', 'parse_buffering', 'parse_buffering_stats', 
'parse_clock_lost', 'parse_clock_provide', 'parse_duration', 'parse_error', 
'parse_info', 'parse_new_clock', 'parse_request_state', 'parse_segment_done', 
'parse_segment_start', 'parse_state_changed', 'parse_step_done', 
'parse_step_start', 'parse_stream_status', 'parse_structure_change', 
'parse_tag', 'parse_tag_full', 'parse_warning', 'set_buffering_stats', 
'set_seqnum', 'src', 'structure', 'timestamp', 'type']



这是点击库内音乐出错时的终端：

Reading http://www.shoutcast.com/sbin/tunein-station.pls?id=1280803
INFO    : Playing http://78.129.250.9:8172
Traceback (most recent call last):
  File "/usr/lib/exaile/xlgui/playlist.py", line 542, in on_row_activated
    self.queue.play(track=track)
  File "/usr/lib/exaile/xl/player/queue.py", line 140, in play
    self.player.play(track)
  File "/usr/lib/exaile/xl/common.py", line 105, in wrapper
    return func(self, *__args, **__kw)
  File "/usr/lib/exaile/xl/player/engine_unified.py", line 206, in play
    time = int(track.get_tag_raw("__length")*1000 - duration)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
ERROR   : <gst.Message GstMessageError, gerror=(GstGError)NULL, 
debug=(string)"gstsouphttpsrc.c\(913\):\ gst_soup_http_src_finished_cb\ \(\):\ 
/GstPipeline:pipeline0/GstBin:Stream0/GstURIDecodeBin:uridecodebin4/GstSoupHTTPS
rc:source:\012libsoup\ status\ code\ 1"; from source at 0xa5d1f80> 
['__class__', '__cmp__', '__delattr__', '__dict__', '__doc__', '__format__', 
'__getattribute__', '__grefcount__', '__gstminiobject_init__', '__gtype__', 
'__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', 
'__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'copy', 'flags', 
'parse_async_start', 'parse_buffering', 'parse_buffering_stats', 
'parse_clock_lost', 'parse_clock_provide', 'parse_duration', 'parse_error', 
'parse_info', 'parse_new_clock', 'parse_request_state', 'parse_segment_done', 
'parse_segment_start', 'parse_state_changed', 'parse_step_done', 
'parse_step_start', 'parse_stream_status', 'parse_structure_change', 
'parse_tag', 'parse_tag_full', 'parse_warning', 'set_buffering_stats', 
'set_seqnum', 'src', 'structure', 'timestamp', 'type']



```

Original comment by `blambinn...@gmail.com` on 25 Jul 2010 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
这个bug应该是exaile自己的，我刚刚试过了不装exaile-cn也有这��
�bug的，是所有豆瓣电台内的歌都不能播放吗
```

Original comment by `billno...@gmail.com` on 25 Jul 2010 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
嗯，豆瓣的都不能放，自带的有些能放有些不能
```

Original comment by `blambinn...@gmail.com` on 25 Jul 2010 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
这个好像跟exaile的渐进效果有关，你试试能不能把设置里的��
�进效果关掉
```

Original comment by `billno...@gmail.com` on 25 Jul 2010 at 11:31

**Comment by GoogleCodeExporter** [comment]
```
额，原来是那个 回放引擎，设置为正常就ok了
```

Original comment by `blambinn...@gmail.com` on 25 Jul 2010 at 12:37

**Comment by GoogleCodeExporter** [comment]
```
从Python 2.6开始已经自带json库了
```

Original comment by `classicn...@gmail.com` on 25 Jul 2010 at 12:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `billno...@gmail.com` on 26 Jul 2010 at 6:31
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
我說下我的情況吧,我到 
https://github.com/sunng87/exaile-doubanfm-plugin/downloads 
下載了doubanfm-0.0.6-exaile032.tar.gz 和 doubanfm-0.0.6b-exaile032.tar.gz 
都不行,提示 Failed to retrieve playlist, try again.
但是我把插件目錄的名字改成"doubanfm2" 
就可以了,"doubanfm"和"doubanfm2"都不行.算是比較奇怪吧...
```

Original comment by `tofuli...@gmail.com` on 20 Dec 2010 at 5:05
