### ISSUE TITLE
豆瓣插件问题

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/exaile-cn#17]
```
先开始是 Failed to retrieve playlist, try again 
按照另外一个问题的解决办法 就没有这个提示了 
但是是还是无法使用 终端有以下输出：

NFO    : Loading Exaile 0.3.2.0...
INFO    : Loading settings...
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Playing file:///media/sdfsd/Music/10_pjharvey_silence_bestof07.mp3
Traceback (most recent call last):
  File "/home/wukong/.local/share/exaile/plugins/doubanfm/__init__.py", line 300, in active_douban_radio
    tracks = map(self.create_track_from_douban_song, songs)
  File "/home/wukong/.local/share/exaile/plugins/doubanfm/__init__.py", line 269, in create_track_from_douban_song
    track = DoubanFMTrack(uri, song['sid'], song['aid'], song['like'])
  File "/usr/local/lib/exaile/xl/trax/track.py", line 142, in __new__
    raise TypeError, "Track cannot be subclassed!"
TypeError: Track cannot be subclassed!

```

Original issue reported on code.google.com by `wlim...@gmail.com` on 26 Jul 2010 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
忘了说了 我的系统是ubuntu 10.04  python 2.65  exaile 0.3.2.0
```

Original comment by `wlim...@gmail.com` on 26 Jul 2010 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
貌似你没有exaile-cn里的将track.py覆盖到/usr/lib/exaile/xl/trax/目录
下
```

Original comment by `billno...@gmail.com` on 26 Jul 2010 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
我把track.py 复制到了 /usr/local/lib/exaile/xl/trax/track.py 问题解决
```

Original comment by `wlim...@gmail.com` on 27 Jul 2010 at 8:29

**Comment by GoogleCodeExporter** [comment]
Original comment by `billno...@gmail.com` on 27 Jul 2010 at 11:00
- Changed state: **Done**
