### ISSUE TITLE
歌词不能显示

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/exaile-cn#2]
```
你好，我运行后其他正常，解决了中文乱码，迷你模式也非��
�好
不过歌词插件不显示歌词，是空白的
终端出现
Traceback (most recent call last):
  File "/home/kswang/.exaile/plugins/lrcPlugin.py", line 381, in lrcList
    self.timeSeek()
  File "/home/kswang/.exaile/plugins/lrcPlugin.py", line 347, in timeSeek
    if time > self.timeLines[-1]:
IndexError: list index out of range

```

Original issue reported on code.google.com by `wangk...@gmail.com` on 27 Aug 2009 at 2:03

Attachments:
- [Screenshot.png](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-2/comment-0/Screenshot.png)

**Comment by GoogleCodeExporter** [comment]
```
你好，你的问题我也遇到了，现在正在努力解决中，初步判��
�是因为千千静听修改了歌词下载方
法所导致的，我会尽快的修复这个问题，谢谢你对exaile-cn的��
�持！
```

Original comment by `billno...@gmail.com` on 27 Aug 2009 at 4:43

**Comment by GoogleCodeExporter** [comment]
```
问题已经解决，请下载最新的v0.87版
```

Original comment by `billno...@gmail.com` on 1 Oct 2009 at 2:19
- Changed state: **Fixed**
