### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/exaile-cn#6]
```
1. 在终端中运行exaile
2. 在exaile的首选项中选择plugins中的Lyric Display

终端中输出
Traceback (most recent call last):
  File "/usr/lib/exaile/xl/plugins.py", line 114, in enable_plugin
    plugin.enable(self.exaile)
  File "/usr/share/exaile/plugins/LyricDisp/__init__.py", line 224, in enable
    _enable(None, exaile, None)
  File "/usr/share/exaile/plugins/LyricDisp/__init__.py", line 242, in _enable
    lrcWinShow(exaile)
  File "/usr/share/exaile/plugins/LyricDisp/__init__.py", line 490, in
lrcWinShow
    PLUGIN.timeSeek()
  File "/usr/share/exaile/plugins/LyricDisp/__init__.py", line 373, in timeSeek
    if time > self.timeLines[-1]:
AttributeError: lrcWin instance has no attribute 'timeLines'
WARNING : Unable to enable plugin LyricDisp


版本：Exaile-cn091121-2.zip
系统：ubuntu9.10 


```

Original issue reported on code.google.com by `topc...@gmail.com` on 1 Dec 2009 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
这个问题还真没有遇到过……你没有修改过歌词插件的代码��
�……我会尽量尝试解决……
```

Original comment by `billno...@gmail.com` on 4 Dec 2009 at 9:20

**Comment by GoogleCodeExporter** [comment]
```
同样的问题，也是Ubuntu9.10， exaile 0.3.0.2-0，从ppa装的
歌词插件不能用呀
```

Original comment by `haohe...@gmail.com` on 15 Dec 2009 at 12:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `haohe...@gmail.com` on 15 Dec 2009 at 12:44

Attachments:
- [截取选区_001.png](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-6/comment-3/截取选区_001.png)

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
这个问题大概是因为你在播放音乐时加载插件的原因，你可��
�停了音乐后在加载插件试试
```

Original comment by `billno...@gmail.com` on 19 Dec 2009 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
问题已修复，请用附件中的文件替换歌词插件
```

Original comment by `billno...@gmail.com` on 19 Dec 2009 at 9:24
- Changed state: **Fixed**

Attachments:
- [lyricdisp.tar.gz](https://storage.googleapis.com/google-code-attachments/exaile-cn/issue-6/comment-7/lyricdisp.tar.gz)
